baseURL = 'https://sisterandsister.ca/'
languageCode = 'en-us'
title = 'SnS | Morkie Puppies'
theme = "raditian"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Puppies"
  URL = "#puppies"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4


  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Puppies"
  URL = "#puppies"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4


[params]

  sections = ["showcase", "about", "puppies", "contact"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Sister &"
    text2 = "Sister"

  [params.footer]
      copyright = "© Sister & Sister. All rights reserved."
#      [params.footer.radity_logo]
#        x = "img/general/design-and-code-radity.png"
#        _2x = "img/general/design-and-code-radity@2x.png"
#        alt = "Design & Code - Radity"